name       : haskell-skylighting-core
version    : 0.7.1
release    : 1
source     :
    - https://hackage.haskell.org/package/skylighting-core-0.7.1/skylighting-core-0.7.1.tar.gz : 4ffe223554db53cedfce5af92a7f22a907904c40bf498777dfdfe3c5ccd8723e
license    : BSD-3-Clause
component  : programming.haskell
summary    : Skylighting is a syntax highlighting library. This package provides the core highlighting functionality.
description: |
    Skylighting is a syntax highlighting library. It derives its tokenizers from XML syntax definitions used by KDE's KSyntaxHighlighting framework, so any syntax supported by that framework can be added. An optional command-line program is provided. Skylighting is intended to be the successor to highlighting-kate. This package provides the core highlighting functionality under a permissive license. It also bundles XML parser definitions licensed under the GPL.
    - haskell-aeson
builddeps  :
    - haskell-aeson
    - haskell-ansi-terminal
    - haskell-base64-bytestring
    - haskell-blaze-html
    - haskell-cabal-install
    - haskell-case-insensitive
    - haskell-hxt
    - haskell-regex-pcre-builtin
    - haskell-safe
    - haskell-utf8-string
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
